<?php

return [
    'guard' => 'web',

    'groups' => [
        'departments' => [
            'departments.view_any' => 'View the list of departments',
            'departments.view' => 'View a single department\'s details',
            'departments.create' => 'Create a new department',
            'departments.update' => 'Update an existing department',
            'departments.delete' => 'Delete a department',
        ],
        'positions' => [
            'positions.view_any' => 'View the list of positions',
            'positions.view' => 'View a single position\'s details',
            'positions.create' => 'Create a new position',
            'positions.update' => 'Update an existing position',
            'positions.delete' => 'Delete a position',
        ],
        'employees' => [
            'employees.view_any' => 'View the list of employees',
            'employees.search' => 'Search employees by name or other attributes',
            'employees.view' => 'View a single employee\'s details',
            'employees.create' => 'Create a new employee',
            'employees.update' => 'Update an existing employee',
            'employees.delete' => 'Delete an employee',
            'employees.update_salary' => 'Update an employee\'s salary information',
        ],
        'company_settings' => [
            'company_settings.view' => 'View company settings',
            'company_settings.update' => 'Update company settings',
        ],
        'public_holidays' => [
            'public_holidays.view_any' => 'View the list of public holidays',
            'public_holidays.view' => 'View a single public holiday\'s details',
            'public_holidays.create' => 'Create a new public holiday',
            'public_holidays.update' => 'Update an existing public holiday',
            'public_holidays.delete' => 'Delete a public holiday',
        ],
        'attendance' => [
            'attendance.view_any' => 'View attendance records for all employees',
            'attendance.view_own' => 'View own attendance records',
            'attendance.view_correction' => 'View attendance correction requests',
            'attendance.clock_in' => 'Clock in for attendance',
            'attendance.clock_out' => 'Clock out for attendance',
            'attendance.correct' => 'Correct an attendance record',
            'attendance.mark_absent' => 'Mark an employee as absent',
            'attendance.proxy_clock' => 'Clock attendance on behalf of another employee',
            'attendance.generate_qr' => 'Generate a QR code for attendance clocking',
        ],
        'leaves' => [
            'leaves.view_any' => 'View leave requests for all employees',
            'leaves.view' => 'View a single leave request\'s details',
            'leaves.view_own' => 'View own leave requests',
            'leaves.create' => 'Create a new leave request',
            'leaves.cancel' => 'Cancel a leave request',
            'leaves.approve' => 'Approve a leave request',
            'leaves.reject' => 'Reject a leave request',
            'leaves.approve_hr' => 'Give HR approval on a leave request',
            'leaves.reject_hr' => 'Give HR rejection on a leave request',
            'leaves.approve_ceo' => 'Give CEO approval on a leave request',
            'leaves.reject_ceo' => 'Give CEO rejection on a leave request',
        ],
        'leave_balances' => [
            'leave_balances.view_any' => 'View leave balances for all employees',
            'leave_balances.view_own' => 'View own leave balance',
        ],
        'payrolls' => [
            'payrolls.view_any' => 'View payroll records for all employees',
            'payrolls.view_own' => 'View own payroll records',
            'payrolls.generate' => 'Generate payroll for a pay period',
            'payrolls.update' => 'Update a payroll record',
            'payrolls.submit' => 'Submit payroll for approval',
            'payrolls.approve' => 'Approve a submitted payroll',
            'payrolls.reject' => 'Reject a submitted payroll',
        ],
        'payslips' => [
            'payslips.view_any' => 'View payslips for all employees',
            'payslips.view_own' => 'View own payslip',
            'payslips.download_any' => 'Download payslips for any employee',
            'payslips.download_own' => 'Download own payslip',
        ],
        'reports' => [
            'reports.payroll_view' => 'View payroll reports',
            'reports.payroll_export' => 'Export payroll reports',
            'reports.attendance_view' => 'View attendance reports',
            'reports.attendance_export' => 'Export attendance reports',
            'reports.leave_view' => 'View leave reports',
            'reports.leave_export' => 'Export leave reports',
        ],
        'audit_logs' => [
            'audit_logs.view' => 'View audit logs',
        ],
        'users' => [
            'users.view_any' => 'View the list of system users',
            'users.search' => 'Search system users',
            'users.view' => 'View a single system user\'s details',
            'users.create' => 'Create a new system user',
            'users.update' => 'Update an existing system user',
            'users.delete' => 'Delete a system user',
            'users.reset_password' => 'Reset a system user\'s password',
            'users.assign_roles' => 'Assign roles to a system user',
            'users.assign_permissions' => 'Assign direct permissions to a system user',
        ],
        'roles_permissions' => [
            'roles_permissions.roles_view' => 'View the list of roles',
            'roles_permissions.permissions_view' => 'View the list of permissions',
            'roles_permissions.manage' => 'Manage role and permission assignments',
        ],
        'backups' => [
            'backups.create' => 'Create a manual database backup',
            'backups.download' => 'Download a database backup',
        ],
        'dashboards' => [
            'dashboards.admin_view' => 'View the admin dashboard',
            'dashboards.hr_view' => 'View the HR dashboard',
            'dashboards.ceo_view' => 'View the CEO dashboard',
            'dashboards.employee_view' => 'View the employee dashboard',
        ],
        'announcements' => [
            'announcements.view' => 'View published announcements',
            'announcements.view_draft' => 'View draft announcements',
            'announcements.create' => 'Create a new announcement',
            'announcements.update' => 'Update an existing announcement',
            'announcements.submit' => 'Submit an announcement for approval',
            'announcements.cancel_submission' => 'Cancel a submitted announcement',
            'announcements.approve' => 'Approve an announcement',
            'announcements.archive' => 'Archive an announcement',
        ],
        'announcement_categories' => [
            'announcement_categories.view' => 'View announcement categories',
            'announcement_categories.create' => 'Create a new announcement category',
            'announcement_categories.update' => 'Update an existing announcement category',
            'announcement_categories.deactivate' => 'Deactivate an announcement category',
        ],
        'recruitment_vacancies' => [
            'recruitment.vacancies.view' => 'View recruitment vacancies',
            'recruitment.vacancies.create' => 'Create a new recruitment vacancy',
            'recruitment.vacancies.update' => 'Update an existing recruitment vacancy',
            'recruitment.vacancies.close' => 'Close a recruitment vacancy',
        ],
        'recruitment_candidates' => [
            'recruitment.candidates.view' => 'View recruitment candidates',
            'recruitment.candidates.create' => 'Create a new recruitment candidate',
            'recruitment.candidates.update' => 'Update an existing recruitment candidate',
            'recruitment.candidates.hire' => 'Hire a recruitment candidate',
        ],
        'employee_upgrade_requests' => [
            'employee_upgrade_requests.view_any' => 'View employee upgrade requests for all employees',
            'employee_upgrade_requests.view' => 'View a single employee upgrade request\'s details',
            'employee_upgrade_requests.create' => 'Create a new employee upgrade request',
            'employee_upgrade_requests.cancel' => 'Cancel an employee upgrade request',
            'employee_upgrade_requests.approve' => 'Approve an employee upgrade request',
            'employee_upgrade_requests.reject' => 'Reject an employee upgrade request',
        ],
    ],

    'roles' => [
        'admin' => [
            'groups' => [
                'users',
                'roles_permissions',
                'backups',
            ],
            'permissions' => [
                'departments.view_any',
                'departments.view',
                'positions.view_any',
                'positions.view',
                'employees.view_any',
                'employees.search',
                'company_settings.view',
                'company_settings.update',
                'public_holidays.view_any',
                'public_holidays.view',
                'attendance.view_any',
                'attendance.view_correction',
                'leaves.view_any',
                'leaves.view',
                'leave_balances.view_any',
                'reports.attendance_view',
                'reports.attendance_export',
                'reports.leave_view',
                'reports.leave_export',
                'audit_logs.view',
                'dashboards.admin_view',
                'announcements.view',
                'announcements.view_draft',
                'announcement_categories.view',
                'recruitment.vacancies.view',
                'recruitment.candidates.view',
                'employee_upgrade_requests.view_any',
                'employee_upgrade_requests.view',
            ],
        ],
        'hr' => [
            'groups' => [
                'departments',
                'positions',
                'employees',
                'public_holidays',
                'reports',
            ],
            'permissions' => [
                'attendance.view_any',
                'attendance.view_own',
                'attendance.view_correction',
                'attendance.clock_in',
                'attendance.clock_out',
                'attendance.correct',
                'attendance.mark_absent',
                'leaves.view_any',
                'leaves.approve_hr',
                'leaves.reject_hr',
                'leave_balances.view_any',
                'leave_balances.view_own',
                'leaves.create',
                'leaves.cancel',
                'payrolls.view_any',
                'payrolls.view_own',
                'payrolls.generate',
                'payrolls.update',
                'payrolls.submit',
                'payslips.view_any',
                'payslips.view_own',
                'payslips.download_any',
                'payslips.download_own',
                'company_settings.view',
                'dashboards.hr_view',
                'attendance.proxy_clock',
                'attendance.generate_qr',
                'announcements.view',
                'announcements.create',
                'announcements.update',
                'announcements.submit',
                'announcements.cancel_submission',
                'announcements.archive',
                'announcement_categories.view',
                'announcements.view_draft',
                'recruitment.vacancies.view',
                'recruitment.vacancies.create',
                'recruitment.vacancies.update',
                'recruitment.vacancies.close',
                'recruitment.candidates.view',
                'recruitment.candidates.create',
                'recruitment.candidates.update',
                'users.view_any',
                'users.search',
                'employee_upgrade_requests.view',
                'employee_upgrade_requests.create',
                'employee_upgrade_requests.cancel',
            ],
        ],
        'ceo' => [
            'permissions' => [
                'attendance.view_any',
                'employees.view_any',
                'employees.view',
                'employees.search',
                'leaves.view_any',
                'leave_balances.view_any',
                'leave_balances.view_own',
                'payrolls.view_any',
                'payrolls.approve',
                'payrolls.reject',
                'payslips.view_any',
                'payslips.download_any',
                'reports.payroll_view',
                'reports.attendance_view',
                'reports.leave_view',
                'audit_logs.view',
                'company_settings.view',
                'dashboards.ceo_view',
                'leaves.approve_ceo',
                'leaves.reject_ceo',
                'announcements.view',
                'announcements.approve',
                'announcement_categories.view',
                'employee_upgrade_requests.view_any',
                'employee_upgrade_requests.view',
                'employee_upgrade_requests.approve',
                'employee_upgrade_requests.reject',
            ],
        ],
        'employee' => [
            'permissions' => [
                'attendance.view_own',
                'attendance.clock_in',
                'attendance.clock_out',
                'leaves.view_own',
                'leaves.create',
                'leaves.cancel',
                'leave_balances.view_own',
                'payslips.view_own',
                'payslips.download_own',
                'dashboards.employee_view',
                'public_holidays.view',
                'public_holidays.view_any',
                'announcements.view',
                'announcement_categories.view',
            ],
        ],
    ],
];
