<?php

return [
    'guard' => 'web',

    'groups' => [
        'departments' => [
            'departments.view_any',
            'departments.view',
            'departments.create',
            'departments.update',
            'departments.delete',
        ],
        'positions' => [
            'positions.view_any',
            'positions.view',
            'positions.create',
            'positions.update',
            'positions.delete',
        ],
        'employees' => [
            'employees.view_any',
            'employees.view',
            'employees.create',
            'employees.update',
            'employees.delete',
            'employees.update_salary',
        ],
        'company_settings' => [
            'company_settings.view',
            'company_settings.update',
        ],
        'public_holidays' => [
            'public_holidays.view_any',
            'public_holidays.view',
            'public_holidays.create',
            'public_holidays.update',
            'public_holidays.delete',
        ],
        'attendance' => [
            'attendance.view_any',
            'attendance.view_own',
            'attendance.clock_in',
            'attendance.clock_out',
            'attendance.correct',
            'attendance.mark_absent',
        ],
        'leaves' => [
            'leaves.view_any',
            'leaves.view_own',
            'leaves.create',
            'leaves.cancel',
            'leaves.approve_hr',
            'leaves.reject_hr',
            'leaves.approve_ceo',
            'leaves.reject_ceo',
        ],
        'leave_balances' => [
            'leave_balances.view_any',
            'leave_balances.view_own',
        ],
        'payrolls' => [
            'payrolls.view_any',
            'payrolls.view_own',
            'payrolls.generate',
            'payrolls.update',
            'payrolls.submit',
            'payrolls.approve',
            'payrolls.reject',
        ],
        'payslips' => [
            'payslips.view_any',
            'payslips.view_own',
            'payslips.download_any',
            'payslips.download_own',
        ],
        'reports' => [
            'reports.payroll_view',
            'reports.payroll_export',
            'reports.attendance_view',
            'reports.attendance_export',
            'reports.leave_view',
            'reports.leave_export',
        ],
        'audit_logs' => [
            'audit_logs.view',
        ],
        'users' => [
            'users.view_any',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.reset_password',
            'users.assign_roles',
        ],
        'roles_permissions' => [
            'roles_permissions.roles_view',
            'roles_permissions.permissions_view',
            'roles_permissions.manage',
        ],
        'backups' => [
            'backups.create',
            'backups.download',
        ],
        'dashboards' => [
            'dashboards.admin_view',
            'dashboards.hr_view',
            'dashboards.ceo_view',
            'dashboards.employee_view',
        ],
    ],

    'roles' => [
        'admin' => [
            'all' => true,
        ],
        'hr' => [
            'groups' => [
                'departments',
                'positions',
                'employees',
                'public_holidays',
                'reports',
            ],
            'permissions' => [
                'attendance.view_any',
                'attendance.view_own',
                'attendance.clock_in',
                'attendance.clock_out',
                'attendance.correct',
                'attendance.mark_absent',
                'leaves.view_any',
                'leaves.view_own',
                'leaves.create',
                'leaves.cancel',
                'leaves.approve_hr',
                'leaves.reject_hr',
                'leave_balances.view_any',
                'leave_balances.view_own',
                'payrolls.view_any',
                'payrolls.view_own',
                'payrolls.generate',
                'payrolls.update',
                'payrolls.submit',
                'payslips.view_any',
                'payslips.view_own',
                'payslips.download_any',
                'payslips.download_own',
                'company_settings.view',
                'dashboards.hr_view',
            ],
        ],
        'ceo' => [
            'permissions' => [
                'attendance.view_any',
                'leaves.view_any',
                'leave_balances.view_any',
                'payrolls.view_any',
                'payrolls.approve',
                'payrolls.reject',
                'payslips.view_any',
                'payslips.download_any',
                'reports.payroll_view',
                'reports.attendance_view',
                'reports.leave_view',
                'audit_logs.view',
                'company_settings.view',
                'dashboards.ceo_view',
                'leaves.approve_ceo',
                'leaves.reject_ceo',
            ],
        ],
        'employee' => [
            'permissions' => [
                'attendance.view_own',
                'attendance.clock_in',
                'attendance.clock_out',
                'leaves.view_own',
                'leaves.create',
                'leaves.cancel',
                'leave_balances.view_own',
                'payslips.view_own',
                'payslips.download_own',
                'dashboards.employee_view',
            ],
        ],
    ],
];
